// Generated by scripts/generate-bricks.mjs — rerun it, never hand-edit.
// Rendered height ÷ width of each whole-row brick variant; index 0 = 1 row.
export const BRICK_ROW_RATIOS = {
  top: [
    0.0547,
    0.0987,
    0.1476,
    0.1908,
    0.2335,
    0.276,
    0.3131,
    0.3553
  ],
  bottom: [
    0.0526,
    0.0946,
    0.1417,
    0.1836,
    0.2243,
    0.2648,
    0.3004,
    0.3409
  ]
} as const;
